<?php
/**
* Implements hook_theme().
*
* We use hook_theme to define the templates used.
*/
function majuelo_custom_theme($existing, $type, $theme, $path) {
 return [
   'majuelo_custom_years_block' => [
     'variables' => [
       'years' => [],
     ],
   ],
   'css_block' => [
     'variables' => [],
   ],
   'js_block' => [
     'variables' => [],
   ],
   'context_block' => [
     'variables' => [
       'name' => NULL,
     ],
   ],
 ];
}